#
# Goldiriath v0.0.1 pre-alpha configuration
#

# Default money
default_money: 10

#Default health
default_health: 100

#default mana
default_mana: 100

# Sign based mob spawner
mobspawner:
    enabled: true

    # Development mode
    # When this is set to true, all mobspawns will be disabled and presented as signs.
    dev_mode: true

    # Radius for mob spawners
    radius: 20

    # Default maximum amount of mobs a spawner can spawn
    max_mobs: 5

    # Minimum delay after a spawn in ticks
    # 600 ticks: 600 / 20 ticks = 30 seconds
    spawn_threshold: 600

    # The radius in which a player must reside in order to start spawning mobs
    # Set to 0 to always spawn.
    player_radius_threshold: 50

# If enabled, dispensers will never run out
infinite_dispenser:
    enabled: true
